package culture

import (
	"persons_generator/tools"
)

var AllCultures = tools.Merge(
	AllAkanCultures,
	AllArabicCultures,
	AllBalticCultures,
	AllBaltoFinnicCultures,
	AllBerberCultures,
	AllBrythonicCultures,
	AllBurmanCultures,
	AllByzantineCultures,
	AllCentralAfricanCultures,
	AllCentralGermanicCultures,
	AllChineseCultures,
	AllDravidianCultures,
	AllEastAfricanCultures,
	AllEastSlavicCultures,
	AllFrankishCultures,
	AllGoidelicCultures,
	AllGuineanUplanderCultures,
	AllHornAfricanCultures,
	AllIberianCultures,
	AllIndoAryanCultures,
	AllIranianCultures,
	AllIsraeliteCultures,
	AllLatinCultures,
	AllMagyarCultures,
	AllMongolicCultures,
	AllNigerDeltaCultures,
	AllNorthGermanicCultures,
	AllQiangicCultures,
	AllSahelianCultures,
	AllSenegambianCultures,
	AllSouthSlavicCultures,
	AllTibetanCultures,
	AllTocharianCultures,
	AllTurkicCultures,
	AllUgroPermianCultures,
	AllVlachCultures,
	AllVolgaFinnicCultures,
	AllWestGermanicCultures,
	AllWestSlavicCultures,
	AllAntiqueCultures,
)
