package culture

// import (
// 	bc "persons_generator/entities/base_culture"
// )

// var MesopotamianMaleNames = []*Name{
// 	{
// 		Culture:       bc.Mesopotamian,
// 		Name:          "Baal",
// 		Sex:           Male,
// 		IsInheritable: true,
// 		Probability:   0.1,
// 	},
// 	{
// 		Culture:       bc.Mesopotamian,
// 		Name:          "Ilu",
// 		Sex:           Male,
// 		IsInheritable: true,
// 		Probability:   0.1,
// 	},
// 	{
// 		Culture:       bc.Mesopotamian,
// 		Name:          "Mummu",
// 		Sex:           Male,
// 		IsInheritable: true,
// 		Probability:   0.1,
// 	},
// 	{
// 		Culture:       bc.Mesopotamian,
// 		Name:          "Zamama",
// 		Sex:           Male,
// 		IsInheritable: true,
// 		Probability:   0.1,
// 	},
// }

// var MesopotamianFemaleNames = []*Name{
// 	{
// 		Culture:       bc.Mesopotamian,
// 		Name:          "Anatu",
// 		Sex:           Female,
// 		IsInheritable: true,
// 		Probability:   0.25,
// 	},
// 	{
// 		Culture:       bc.Mesopotamian,
// 		Name:          "Lilith",
// 		Sex:           Female,
// 		IsInheritable: true,
// 		Probability:   0.25,
// 	},
// 	{
// 		Culture:       bc.Mesopotamian,
// 		Name:          "Mot",
// 		Sex:           Female,
// 		IsInheritable: true,
// 		Probability:   0.1,
// 	},
// 	{
// 		Culture:       bc.Mesopotamian,
// 		Name:          "Tiamat",
// 		Sex:           Female,
// 		IsInheritable: true,
// 		Probability:   0.25,
// 	},
// }

// var BabylonianMaleNames = []*Name{
// 	{
// 		Culture:     bc.Babylonian,
// 		Name:        "Adrahasis",
// 		Sex:         Male,
// 		Probability: 0.1,
// 	},
// 	{
// 		Culture:     bc.Babylonian,
// 		Name:        "Allamu",
// 		Sex:         Male,
// 		Probability: 0.1,
// 	},
// 	{
// 		Culture:     bc.Babylonian,
// 		Name:        "Apsu",
// 		Sex:         Male,
// 		Probability: 0.1,
// 	},
// 	{
// 		Culture:     bc.Babylonian,
// 		Name:        "Balasi",
// 		Sex:         Male,
// 		Probability: 0.1,
// 	},
// 	{
// 		Culture:     bc.Babylonian,
// 		Name:        "Bel",
// 		Sex:         Male,
// 		Probability: 0.25,
// 	},
// 	{
// 		Culture:     bc.Babylonian,
// 		Name:        "Belshazzar",
// 		Sex:         Male,
// 		Probability: 0.25,
// 	},
// 	{
// 		Culture:     bc.Babylonian,
// 		Name:        "Berossus",
// 		Sex:         Male,
// 		Probability: 0.1,
// 	},
// 	{
// 		Culture:     bc.Babylonian,
// 		Name:        "Cit",
// 		Sex:         Male,
// 		Probability: 0.25,
// 	},
// 	{
// 		Culture:     bc.Babylonian,
// 		Name:        "Dagan",
// 		Sex:         Male,
// 		Probability: 0.25,
// 	},
// 	{
// 		Culture:     bc.Babylonian,
// 		Name:        "Enmeduranki",
// 		Sex:         Male,
// 		Probability: 0.05,
// 	},
// 	{
// 		Culture:     bc.Babylonian,
// 		Name:        "Haldita",
// 		Sex:         Male,
// 		Probability: 0.1,
// 	},
// 	{
// 		Culture:     bc.Babylonian,
// 		Name:        "Hammurabi",
// 		Sex:         Male,
// 		Probability: 0.25,
// 	},
// 	{
// 		Culture:     bc.Babylonian,
// 		Name:        "Harbishihu",
// 		Sex:         Male,
// 		Probability: 0.05,
// 	},
// 	{
// 		Culture:     bc.Babylonian,
// 		Name:        "Ibilsin",
// 		Sex:         Male,
// 		Probability: 0.1,
// 	},
// 	{
// 		Culture:     bc.Babylonian,
// 		Name:        "Idadu",
// 		Sex:         Male,
// 		Probability: 0.25,
// 	},
// 	{
// 		Culture:     bc.Babylonian,
// 		Name:        "Igigi",
// 		Sex:         Male,
// 		Probability: 0.1,
// 	},
// 	{
// 		Culture:     bc.Babylonian,
// 		Name:        "Irshusin",
// 		Sex:         Male,
// 		Probability: 0.25,
// 	},
// 	{
// 		Culture:     bc.Babylonian,
// 		Name:        "Izdubar",
// 		Sex:         Male,
// 		Probability: 0.25,
// 	},
// 	{
// 		Culture:     bc.Babylonian,
// 		Name:        "Kingu",
// 		Sex:         Male,
// 		Probability: 0.25,
// 	},
// 	{
// 		Culture:     bc.Babylonian,
// 		Name:        "Kinziru",
// 		Sex:         Male,
// 		Probability: 0.25,
// 	},
// 	{
// 		Culture:     bc.Babylonian,
// 		Name:        "Kissare",
// 		Sex:         Male,
// 		Probability: 0.25,
// 	},
// 	{
// 		Culture:     bc.Babylonian,
// 		Name:        "Laborosoarchod",
// 		Sex:         Male,
// 		Probability: 0.05,
// 	},
// 	{
// 		Culture:     bc.Babylonian,
// 		Name:        "Lakhmu",
// 		Sex:         Male,
// 		Probability: 0.25,
// 	},
// 	{
// 		Culture:     bc.Babylonian,
// 		Name:        "Makru",
// 		Sex:         Male,
// 		Probability: 0.25,
// 	},
// 	{
// 		Culture:     bc.Babylonian,
// 		Name:        "Marduk",
// 		Sex:         Male,
// 		Probability: 0.25,
// 	},
// 	{
// 		Culture:     bc.Babylonian,
// 		Name:        "Merodach",
// 		Sex:         Male,
// 		Probability: 0.25,
// 	},
// 	{
// 		Culture:     bc.Babylonian,
// 		Name:        "Mulagunnuna",
// 		Sex:         Male,
// 		Probability: 0.1,
// 	},
// 	{
// 		Culture:     bc.Babylonian,
// 		Name:        "Muranu",
// 		Sex:         Male,
// 		Probability: 0.25,
// 	},
// 	{
// 		Culture:     bc.Babylonian,
// 		Name:        "Nabonahid",
// 		Sex:         Male,
// 		Probability: 0.1,
// 	},
// 	{
// 		Culture:     bc.Babylonian,
// 		Name:        "Nabonassar",
// 		Sex:         Male,
// 		Probability: 0.1,
// 	},
// 	{
// 		Culture:     bc.Babylonian,
// 		Name:        "Nabopalassar",
// 		Sex:         Male,
// 		Probability: 0.1,
// 	},
// 	{
// 		Culture:     bc.Babylonian,
// 		Name:        "Nabuchodrosser",
// 		Sex:         Male,
// 		Probability: 0.1,
// 	},
// 	{
// 		Culture:     bc.Babylonian,
// 		Name:        "Naditabirus",
// 		Sex:         Male,
// 		Probability: 0.1,
// 	},
// 	{
// 		Culture:     bc.Babylonian,
// 		Name:        "Namtar",
// 		Sex:         Male,
// 		Probability: 0.25,
// 	},
// 	{
// 		Culture:     bc.Babylonian,
// 		Name:        "Nanna",
// 		Sex:         Male,
// 		Probability: 0.1,
// 	},
// 	{
// 		Culture:     bc.Babylonian,
// 		Name:        "Nebo",
// 		Sex:         Male,
// 		Probability: 0.25,
// 	},
// 	{
// 		Culture:     bc.Babylonian,
// 		Name:        "Nergal",
// 		Sex:         Male,
// 		Probability: 0.15,
// 	},
// 	{
// 		Culture:     bc.Babylonian,
// 		Name:        "Ninib",
// 		Sex:         Male,
// 		Probability: 0.25,
// 	},
// 	{
// 		Culture:     bc.Babylonian,
// 		Name:        "Nurval",
// 		Sex:         Male,
// 		Probability: 0.25,
// 	},
// 	{
// 		Culture:     bc.Babylonian,
// 		Name:        "Nusku",
// 		Sex:         Male,
// 		Probability: 0.25,
// 	},
// 	{
// 		Culture:     bc.Babylonian,
// 		Name:        "Otiartes",
// 		Sex:         Male,
// 		Probability: 0.1,
// 	},
// 	{
// 		Culture:     bc.Babylonian,
// 		Name:        "Pahas-bel",
// 		Sex:         Male,
// 		Probability: 0.1,
// 	},
// 	{
// 		Culture:     bc.Babylonian,
// 		Name:        "Ramman",
// 		Sex:         Male,
// 		Probability: 0.25,
// 	},
// 	{
// 		Culture:     bc.Babylonian,
// 		Name:        "Riisvul",
// 		Sex:         Male,
// 		Probability: 0.1,
// 	},
// 	{
// 		Culture:     bc.Babylonian,
// 		Name:        "Rim-agu",
// 		Sex:         Male,
// 		Probability: 0.1,
// 	},
// 	{
// 		Culture:     bc.Babylonian,
// 		Name:        "Rimsin",
// 		Sex:         Male,
// 		Probability: 0.25,
// 	},
// 	{
// 		Culture:     bc.Babylonian,
// 		Name:        "Saga-saltiyas",
// 		Sex:         Male,
// 		Probability: 0.1,
// 	},
// 	{
// 		Culture:     bc.Babylonian,
// 		Name:        "Sar",
// 		Sex:         Male,
// 		Probability: 0.25,
// 	},
// 	{
// 		Culture:     bc.Babylonian,
// 		Name:        "Sardanapalus",
// 		Sex:         Male,
// 		Probability: 0.1,
// 	},
// 	{
// 		Culture:     bc.Babylonian,
// 		Name:        "Sargina",
// 		Sex:         Male,
// 		Probability: 0.25,
// 	},
// 	{
// 		Culture:     bc.Babylonian,
// 		Name:        "Shamas",
// 		Sex:         Male,
// 		Probability: 0.25,
// 	},
// 	{
// 		Culture:     bc.Babylonian,
// 		Name:        "Sibi",
// 		Sex:         Male,
// 		Probability: 0.25,
// 	},
// 	{
// 		Culture:     bc.Babylonian,
// 		Name:        "Sige",
// 		Sex:         Male,
// 		Probability: 0.25,
// 	},
// 	{
// 		Culture:     bc.Babylonian,
// 		Name:        "Tammuz",
// 		Sex:         Male,
// 		Probability: 0.25,
// 	},
// 	{
// 		Culture:     bc.Babylonian,
// 		Name:        "Tamzi",
// 		Sex:         Male,
// 		Probability: 0.25,
// 	},
// 	{
// 		Culture:     bc.Babylonian,
// 		Name:        "Tu",
// 		Sex:         Male,
// 		Probability: 0.1,
// 	},
// 	{
// 		Culture:     bc.Babylonian,
// 		Name:        "Ubaratutu",
// 		Sex:         Male,
// 		Probability: 0.1,
// 	},
// 	{
// 		Culture:     bc.Babylonian,
// 		Name:        "Ulam-Khala",
// 		Sex:         Male,
// 		Probability: 0.1,
// 	},
// 	{
// 		Culture:     bc.Babylonian,
// 		Name:        "Ummiah-ziriti",
// 		Sex:         Male,
// 		Probability: 0.1,
// 	},
// 	{
// 		Culture:     bc.Babylonian,
// 		Name:        "Ur",
// 		Sex:         Male,
// 		Probability: 0.25,
// 	},
// 	{
// 		Culture:     bc.Babylonian,
// 		Name:        "Uras",
// 		Sex:         Male,
// 		Probability: 0.25,
// 	},
// 	{
// 		Culture:     bc.Babylonian,
// 		Name:        "Urhammu",
// 		Sex:         Male,
// 		Probability: 0.25,
// 	},
// 	{
// 		Culture:     bc.Babylonian,
// 		Name:        "Urhamsi",
// 		Sex:         Male,
// 		Probability: 0.25,
// 	},
// 	{
// 		Culture:     bc.Babylonian,
// 		Name:        "Urukh",
// 		Sex:         Male,
// 		Probability: 0.25,
// 	},
// 	{
// 		Culture:     bc.Babylonian,
// 		Name:        "Utultar",
// 		Sex:         Male,
// 		Probability: 0.25,
// 	},
// 	{
// 		Culture:     bc.Babylonian,
// 		Name:        "Zabu",
// 		Sex:         Male,
// 		Probability: 0.25,
// 	},
// 	{
// 		Culture:     bc.Babylonian,
// 		Name:        "Zaidu",
// 		Sex:         Male,
// 		Probability: 0.25,
// 	},
// 	{
// 		Culture:     bc.Babylonian,
// 		Name:        "Zamana",
// 		Sex:         Male,
// 		Probability: 0.25,
// 	},
// 	{
// 		Culture:     bc.Babylonian,
// 		Name:        "Zicu",
// 		Sex:         Male,
// 		Probability: 0.25,
// 	},
// }

// var BabylonianFemaleNames = []*Name{
// 	{
// 		Culture:     bc.Babylonian,
// 		Name:        "Anunit",
// 		Sex:         Female,
// 		Probability: 0.25,
// 	},
// 	{
// 		Culture:     bc.Babylonian,
// 		Name:        "Aralu",
// 		Sex:         Female,
// 		Probability: 0.25,
// 	},
// 	{
// 		Culture:     bc.Babylonian,
// 		Name:        "Aruru",
// 		Sex:         Female,
// 		Probability: 0.25,
// 	},
// 	{
// 		Culture:     bc.Babylonian,
// 		Name:        "Bau",
// 		Sex:         Female,
// 		Probability: 0.1,
// 	},
// 	{
// 		Culture:     bc.Babylonian,
// 		Name:        "Belatsunat",
// 		Sex:         Female,
// 		Probability: 0.1,
// 	},
// 	{
// 		Culture:     bc.Babylonian,
// 		Name:        "Belili",
// 		Sex:         Female,
// 		Probability: 0.25,
// 	},
// 	{
// 		Culture:     bc.Babylonian,
// 		Name:        "Beltis",
// 		Sex:         Female,
// 		Probability: 0.25,
// 	},
// 	{
// 		Culture:     bc.Babylonian,
// 		Name:        "Damkina",
// 		Sex:         Female,
// 		Probability: 0.1,
// 	},
// 	{
// 		Culture:     bc.Babylonian,
// 		Name:        "Davke",
// 		Sex:         Female,
// 		Probability: 0.1,
// 	},
// 	{
// 		Culture:     bc.Babylonian,
// 		Name:        "Gaga",
// 		Sex:         Female,
// 		Probability: 0.1,
// 	},
// 	{
// 		Culture:     bc.Babylonian,
// 		Name:        "Gula",
// 		Sex:         Female,
// 		Probability: 0.25,
// 	},
// 	{
// 		Culture:     bc.Babylonian,
// 		Name:        "Ishtar",
// 		Sex:         Female,
// 		Probability: 0.25,
// 	},
// 	{
// 		Culture:     bc.Babylonian,
// 		Name:        "Kalumtum",
// 		Sex:         Female,
// 		Probability: 0.25,
// 	},
// 	{
// 		Culture:     bc.Babylonian,
// 		Name:        "Kishar",
// 		Sex:         Female,
// 		Probability: 0.25,
// 	},
// 	{
// 		Culture:     bc.Babylonian,
// 		Name:        "Mylitta",
// 		Sex:         Female,
// 		Probability: 0.25,
// 	},
// 	{
// 		Culture:     bc.Babylonian,
// 		Name:        "Omarosa",
// 		Sex:         Female,
// 		Probability: 0.25,
// 	},
// 	{
// 		Culture:     bc.Babylonian,
// 		Name:        "Sabitum",
// 		Sex:         Female,
// 		Probability: 0.25,
// 	},
// 	{
// 		Culture:     bc.Babylonian,
// 		Name:        "Sarpanitum",
// 		Sex:         Female,
// 		Probability: 0.1,
// 	},
// 	{
// 		Culture:     bc.Babylonian,
// 		Name:        "Shala",
// 		Sex:         Female,
// 		Probability: 0.25,
// 	},
// 	{
// 		Culture:     bc.Babylonian,
// 		Name:        "Sybella",
// 		Sex:         Female,
// 		Probability: 0.25,
// 	},
// 	{
// 		Culture:     bc.Babylonian,
// 		Name:        "Tashmitum",
// 		Sex:         Female,
// 		Probability: 0.1,
// 	},
// 	{
// 		Culture:     bc.Babylonian,
// 		Name:        "Zirratbanit",
// 		Sex:         Female,
// 		Probability: 0.1,
// 	},
// }

// var EgyptianMaleNames = []*Name{
// 	{
// 		Culture:     bc.Egyptian,
// 		Name:        "Abasi",
// 		Sex:         Male,
// 		Probability: 0.25,
// 	},
// 	{
// 		Culture:     bc.Egyptian,
// 		Name:        "Abayomi",
// 		Sex:         Male,
// 		Probability: 0.1,
// 	},
// 	{
// 		Culture:     bc.Egyptian,
// 		Name:        "Adeben",
// 		Sex:         Male,
// 		Probability: 0.1,
// 	},
// 	{
// 		Culture:     bc.Egyptian,
// 		Name:        "Adio",
// 		Sex:         Male,
// 		Probability: 0.25,
// 	},
// 	{
// 		Culture:     bc.Egyptian,
// 		Name:        "Adofo",
// 		Sex:         Male,
// 		Probability: 0.25,
// 	},
// 	{
// 		Culture:     bc.Egyptian,
// 		Name:        "Adom",
// 		Sex:         Male,
// 		Probability: 0.25,
// 	},
// 	{
// 		Culture:     bc.Egyptian,
// 		Name:        "Akhenaten",
// 		Sex:         Male,
// 		Probability: 0.25,
// 	},
// 	{
// 		Culture:     bc.Egyptian,
// 		Name:        "Akiiki",
// 		Sex:         Male,
// 		Probability: 0.25,
// 	},
// 	{
// 		Culture:     bc.Egyptian,
// 		Name:        "Akil",
// 		Sex:         Male,
// 		Probability: 0.25,
// 	},
// 	{
// 		Culture:     bc.Egyptian,
// 		Name:        "Akins",
// 		Sex:         Male,
// 		Probability: 0.25,
// 	},
// 	{
// 		Culture:     bc.Egyptian,
// 		Name:        "Amen",
// 		Sex:         Male,
// 		Probability: 0.25,
// 	},
// 	{
// 		Culture:     bc.Egyptian,
// 		Name:        "Amenhotep",
// 		Sex:         Male,
// 		Probability: 0.25,
// 	},
// 	{
// 		Culture:     bc.Egyptian,
// 		Name:        "Amenophis",
// 		Sex:         Male,
// 		Probability: 0.25,
// 	},
// 	{
// 		Culture:     bc.Egyptian,
// 		Name:        "Ammon",
// 		Sex:         Male,
// 		Probability: 0.25,
// 	},
// 	{
// 		Culture:     bc.Egyptian,
// 		Name:        "Amsi",
// 		Sex:         Male,
// 		Probability: 0.25,
// 	},
// 	{
// 		Culture:     bc.Egyptian,
// 		Name:        "Amsu",
// 		Sex:         Male,
// 		Probability: 0.25,
// 	},
// 	{
// 		Culture:     bc.Egyptian,
// 		Name:        "Amun",
// 		Sex:         Male,
// 		Probability: 0.25,
// 	},
// 	{
// 		Culture:     bc.Egyptian,
// 		Name:        "Anpu",
// 		Sex:         Male,
// 		Probability: 0.25,
// 	},
// 	{
// 		Culture:     bc.Egyptian,
// 		Name:        "Anubis",
// 		Sex:         Male,
// 		Probability: 0.25,
// 	},
// 	{
// 		Culture:     bc.Egyptian,
// 		Name:        "Anum",
// 		Sex:         Male,
// 		Probability: 0.25,
// 	},
// 	{
// 		Culture:     bc.Egyptian,
// 		Name:        "Anzety",
// 		Sex:         Male,
// 		Probability: 0.25,
// 	},
// 	{
// 		Culture:     bc.Egyptian,
// 		Name:        "Apis",
// 		Sex:         Male,
// 		Probability: 0.25,
// 	},
// 	{
// 		Culture:     bc.Egyptian,
// 		Name:        "Asim",
// 		Sex:         Male,
// 		Probability: 0.25,
// 	},
// 	{
// 		Culture:     bc.Egyptian,
// 		Name:        "Astennu",
// 		Sex:         Male,
// 		Probability: 0.25,
// 	},
// 	{
// 		Culture:     bc.Egyptian,
// 		Name:        "Aswad",
// 		Sex:         Male,
// 		Probability: 0.25,
// 	},
// 	{
// 		Culture:     bc.Egyptian,
// 		Name:        "Ata",
// 		Sex:         Male,
// 		Probability: 0.25,
// 	},
// 	{
// 		Culture:     bc.Egyptian,
// 		Name:        "Atemu",
// 		Sex:         Male,
// 		Probability: 0.25,
// 	},
// 	{
// 		Culture:     bc.Egyptian,
// 		Name:        "Aten",
// 		Sex:         Male,
// 		Probability: 0.25,
// 	},
// 	{
// 		Culture:     bc.Egyptian,
// 		Name:        "Atsu",
// 		Sex:         Male,
// 		Probability: 0.25,
// 	},
// 	{
// 		Culture:     bc.Egyptian,
// 		Name:        "Atum",
// 		Sex:         Male,
// 		Probability: 0.25,
// 	},
// 	{
// 		Culture:     bc.Egyptian,
// 		Name:        "Ausar",
// 		Sex:         Male,
// 		Probability: 0.25,
// 	},
// 	{
// 		Culture:     bc.Egyptian,
// 		Name:        "Azibo",
// 		Sex:         Male,
// 		Probability: 0.25,
// 	},
// 	{
// 		Culture:     bc.Egyptian,
// 		Name:        "Azizi",
// 		Sex:         Male,
// 		Probability: 0.25,
// 	},
// 	{
// 		Culture:     bc.Egyptian,
// 		Name:        "Badru",
// 		Sex:         Male,
// 		Probability: 0.25,
// 	},
// 	{
// 		Culture:     bc.Egyptian,
// 		Name:        "Bakari",
// 		Sex:         Male,
// 		Probability: 0.25,
// 	},
// 	{
// 		Culture:     bc.Egyptian,
// 		Name:        "Baniti",
// 		Sex:         Male,
// 		Probability: 0.25,
// 	},
// 	{
// 		Culture:     bc.Egyptian,
// 		Name:        "Bastet",
// 		Sex:         Male,
// 		Probability: 0.25,
// 	},
// 	{
// 		Culture:     bc.Egyptian,
// 		Name:        "Beb",
// 		Sex:         Male,
// 		Probability: 0.1,
// 	},
// 	{
// 		Culture:     bc.Egyptian,
// 		Name:        "Bebti",
// 		Sex:         Male,
// 		Probability: 0.25,
// 	},
// 	{
// 		Culture:     bc.Egyptian,
// 		Name:        "Bes",
// 		Sex:         Male,
// 		Probability: 0.1,
// 	},
// 	{
// 		Culture:     bc.Egyptian,
// 		Name:        "Bomani",
// 		Sex:         Male,
// 		Probability: 0.25,
// 	},
// 	{
// 		Culture:     bc.Egyptian,
// 		Name:        "Chafulumisa",
// 		Sex:         Male,
// 		Probability: 0.25,
// 	},
// 	{
// 		Culture:     bc.Egyptian,
// 		Name:        "Chaths",
// 		Sex:         Male,
// 		Probability: 0.25,
// 	},
// 	{
// 		Culture:     bc.Egyptian,
// 		Name:        "Chatuluka",
// 		Sex:         Male,
// 		Probability: 0.15,
// 	},
// 	{
// 		Culture:     bc.Egyptian,
// 		Name:        "Chenzira",
// 		Sex:         Male,
// 		Probability: 0.25,
// 	},
// 	{
// 		Culture:     bc.Egyptian,
// 		Name:        "Cheops",
// 		Sex:         Male,
// 		Probability: 0.25,
// 	},
// }

// var EgyptianFemaleNames = []*Name{
// 	{
// 		Culture:     bc.Egyptian,
// 		Sex:         Female,
// 		Name:        "Acenath",
// 		Probability: 0.25,
// 	},
// 	{
// 		Culture:     bc.Egyptian,
// 		Sex:         Female,
// 		Name:        "Ain",
// 		Probability: 0.15,
// 	},
// 	{
// 		Culture:     bc.Egyptian,
// 		Sex:         Female,
// 		Name:        "Akila",
// 		Probability: 0.25,
// 	},
// 	{
// 		Culture:     bc.Egyptian,
// 		Sex:         Female,
// 		Name:        "Amunet",
// 		Probability: 0.25,
// 	},
// 	{
// 		Culture:     bc.Egyptian,
// 		Sex:         Female,
// 		Name:        "Anat",
// 		Probability: 0.25,
// 	},
// 	{
// 		Culture:     bc.Egyptian,
// 		Sex:         Female,
// 		Name:        "Anippe",
// 		Probability: 0.25,
// 	},
// 	{
// 		Culture:     bc.Egyptian,
// 		Sex:         Female,
// 		Name:        "Asenath",
// 		Probability: 0.25,
// 	},
// 	{
// 		Culture:     bc.Egyptian,
// 		Sex:         Female,
// 		Name:        "Astarte",
// 		Probability: 0.25,
// 	},
// 	{
// 		Culture:     bc.Egyptian,
// 		Sex:         Female,
// 		Name:        "Auset",
// 		Probability: 0.15,
// 	},
// 	{
// 		Culture:     bc.Egyptian,
// 		Sex:         Female,
// 		Name:        "Aziza",
// 		Probability: 0.25,
// 	},
// 	{
// 		Culture:     bc.Egyptian,
// 		Sex:         Female,
// 		Name:        "Bahiti",
// 		Probability: 0.25,
// 	},
// 	{
// 		Culture:     bc.Egyptian,
// 		Sex:         Female,
// 		Name:        "Bast",
// 		Probability: 0.25,
// 	},
// 	{
// 		Culture:     bc.Egyptian,
// 		Sex:         Female,
// 		Name:        "Bastet",
// 		Probability: 0.25,
// 	},
// 	{
// 		Culture:     bc.Egyptian,
// 		Sex:         Female,
// 		Name:        "Bennu",
// 		Probability: 0.25,
// 	},
// }
