package religion

const (
	GodOfKingCultCultName            = "god_of_king_cult"
	GodOfProsperityAndWealthCultName = "god_of_prosperity_and_wealth"
	CultOfJusticeCultName            = "cult_of_justice"
	GodOfWarCultName                 = "god_of_war"
	PatronSaintOfMerchantsCultName   = "patron_saint_of_merchants"
	GodOfDeathCultName               = "god_of_death"
	GodOfWisdomCultName              = "god_of_wisdom"
	GodOfSeaCultName                 = "god_of_sea"
	GodOfLoveCultName                = "god_of_love"
	SunWorshipCultName               = "sun_worship"
	MoonWorshipCultName              = "moon_worship"
	GodOfWineCultName                = "god_of_wine"
	GodOfThunderCultName             = "god_of_thunder"
	MotherGoddessCultName            = "mother_goddess"
	HolyAnimalsCultName              = "holy_animals"
	HolyPlantsCultName               = "holy_plants"
	HolyFungusCultName               = "holy_fungus"
	HolyParasiteCultName             = "holy_parasite"
	HolyInsectsCultName              = "holy_insects"
	HolyStonesCultName               = "holy_stones"
	HolyRiverCultName                = "holy_river"
	HolyLakeCultName                 = "holy_lake"
	HolyMountainCultName             = "holy_mountain"
	AncestorWorshipCultName          = "ancestor_worship"
	TricksterCultName                = "trickster"
	SpiritsOfDeathCultName           = "spirits_of_death"
)
