package religion

const (
	RaisingAnimalsTabooName           = "raising_animals"
	RaisingPlantsTabooName            = "raising_plants"
	RaisingFungusTabooName            = "raising_fungus"
	EatAnimalsTabooName               = "eat_animals"
	EatSomeAnimalsTabooName           = "eat_some_animals"
	EatInsectsTabooName               = "eat_insects"
	EatFungusTabooName                = "eat_fungus"
	CannibalismTabooName              = "cannibalism"
	DrinkingBloodTabooName            = "drinking_blood"
	DrinkingStrongAlcoholTabooName    = "drinking_strong_alcohol"
	DrinkingNotStrongAlcoholTabooName = "drinking_not_strong_alcohol"
	UseNicotineTabooName              = "use_nicotine"
	UseCannabisTabooName              = "use_cannabis"
	UseHallucinogensTabooName         = "use_hallucinogens"
	UseCMSStimulantsTabooName         = "use_cns_stimulants"
	UseOpiumTabooName                 = "use_opium"
	SameSexRelationsTabooName         = "same_sex_relations"
	MaleAdulteryTabooName             = "male_adultery"
	FemaleAdulteryTabooName           = "female_adultery"
	SexualDeviancyTabooName           = "sexual_deviancy"
	ProstitutionTabooName             = "prostitution"
	KillAnyoneTabooName               = "kill_anyone"
	KillAnimalsTabooName              = "kill_animals"
	KillHollyAnimalsTabooName         = "kill_holly_animals"
	KillHumansTabooName               = "kill_humans"
	KinslayingTabooName               = "kinslaying"
	SuicideTabooName                  = "suicide"
	TattoosTabooName                  = "tattoos"
	WitchcraftTabooName               = "witchcraft"
	NudismTabooName                   = "nudism"
)
